### ISSUE TITLE
#radio file not found　 /bin/ds_fmc_appd

### ISSUE THREAD

**Issue by lawnn** [kyasu/android_vendor_samsung_hltedcm#1]
上記のファイルが足りてないようです

このファイルが何に必要なのか完全に理解してませんが init.qcom.comにも書いてあるので何かに必要なんだと思います

**Comment by kyasu** [comment]
ご指摘ありがとうございます。
CM13.0は、モデムがSC01FOMUBMIF(4.3)で、vendorのradioがN9005XXUGBOK6(5.0)という変則的な組み合わせで動かしていますが、少しデータ通信の動作がおかしいです。4.4以下のvendorにはds_fmc_appdがあるのですが、5.0のvendorにはds_fmc_appdがありません。試しに、4.4のds_fmc_appdを追加して試してみましたが、私のビルドでは特に動作に変わりはなかったです。
ちなみに、CM12.1は、SC01FOMUGOI4(5.0)のモデムとvendorのradioで、ばっちりデータ通信は動作しています。
時間がなくて試していませんが、mondrianlteのradio関係が参考になるかもしれません。

**Comment by lawnn** [comment]
返信ありがとうございます。
そちらの方も参考にさせてもらいます。

自分の場合は galaxy j (sc02f)なのであまり参考にならないかもしれませんがN9005のvendorを使用した場合にLTEに繋がらなかったので代わりにtemasek氏のcommitを参考にしてN900のvendorを使用したらLTEは掴むようになりました。
ただし再起動時にNetwork operatorsの再設定が必要になる不具合があります。
更にN900の上にSC02F_LPを上書きした場合はデータ通信が不可能になるもののNetwrok operatorsの不具合が直ってました。
更に更にklteのlibril.soとlibsec-ril.soを上書きした場合の挙動はLTEと3Gは掴むもののやはりNetwork operatorsの不具合がでました。

**Comment by kyasu** [comment]
すでにクローズ済みですが、コメントです。
sc-01fとsc-02fは多分中身はほとんど同じような気がします。
また、temasek氏のcommitは、N900W8(カナダ版)だと思います。

こちらのデータ通信の状況ですが、Network operatorsの再設定なしで、LTEを掴みます。起動時は3Gしか掴みませんが、優先ネットワークタイプをLTE->3G->LTEにすると、LTEを掴みます。

こちらの不具合は、WIFIからデータ通信の切り替え時に、データ通信(3G/LTE)を掴まなくなることです。機内モードのON/OFFでデータ通信を再開できますが、不便です。ただし、この不具合には、ワークアラウンドがあることに気が付きました。開発者向けオプションの「モバイルデータを常にON」を有効にすることで、この不具合を回避できます。SamsungQcomRIL.javaの中でこのオプションを強制的に有効にする予定です。

**Comment by lawnn** [comment]
とりあえず上記の題目に関してデータ関連にあまり関係なさそうだったので一旦閉めました。
宣言した方がよかったですね。すみません。

それとsc-01fがどういう挙動をしてるのか知らなかったものでそういった情報提供は助かります。
あと、今のうちの環境で(klteのril関係をmergeしたもので)WIFIの切り替えでもデータ関連が繋がってたのでひとまずこのままで様子見してました。
SC02Fの場合N9005でどいう挙動をしてたのか忘れてしまったのでまた実験してみようかと思います。

**Comment by kyasu** [comment]
コメントありがとうございます。
一旦閉めたのに、コメントを追加して申し訳ありません。
こちらも大変参考になりました。klteのrilで繋がることも確認できましたが、WIFIから切り替え時の動作は改善されなかったので、こちらは現状のままにしています。
ありがとうございました。
